### ISSUE TITLE
BS3: navbar-right

### ISSUE THREAD

**Issue by peshi** [ShPakvel/simple_navigation_renderers#4]
Any chance of implementing navbar-right for Bootstrap 3 ?

```
<ul class="nav navbar-nav navbar-right">
..
</ul>
```

**Comment by peshi** [comment]
Actually I solved it by using different contexts and context.dom_class

But an alignment option would still be nice :+1:

**Comment by ShPakvel** [comment]
Hi, Roland.

Actually, I didn't add this option cause I didn't see the necessity of it.
I mean no need to add my own option when there is such option through general `simple_navigation` gem.
Following is simple example of adding this class to ul tag, which is primary item container:

``` ruby
navigation.items do |primary|
  primary.item :news, "News", news_index_path
  primary.dom_class = 'navbar-right'
end
```

As you can see everything you was needed is line `primary.dom_class = 'navbar-right'` in your navigation config file.

Maybe I just need such example in readme file. What do you think?
And do you still think that it would be better to have my own special option for this?

Thank for your opinion and interest to my project.
/Pavel

**Comment by peshi** [comment]
@ShPakvel Thanks for the follow up and sorry for the late response. I solved just like you mentioned.
I think an example would be really helpful in the readme/documentation.

Thanks for this little gem :+1:
