### ISSUE TITLE
nested items

### ISSUE THREAD

**Issue by cfc1020** [ShPakvel/simple_navigation_renderers#5]
Hi. I have a this problem. When 
`primary.item :catalog, "Catalog", root_path do |section_item|`
Catalog link is show `Catalog <b class="caret"></b>` and many other problem.
what do I do?

**Comment by ShPakvel** [comment]
Hi, Andrey.

I am not sure that I understand everything correctly from your description.
Probably you have the same problem as one discussed in issue #3.

If it is your problem then change the [`consider_item_names_as_safe`](https://github.com/codeplant/simple-navigation/blob/master/generators/navigation_config/templates/config/navigation.rb#L34-L35) parameter to `true` in your configuration file.

If it is not what you meant please explain you problem in more details, and I will try to help you.

/Pavel
